import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: " Darul Huda Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="true"
        className={` flex h-screen w-screen  overflow-x-hidden`}
        data-theme="winter"
      >
        <Navbar />
        <div className="w-5/6 py-4 px-5 ">{children}</div>
      </body>
    </html>
  );
}
