import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: " Darul Huda Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white h-dvh">
      <body
        cz-shortcut-listen="true"
        className="flex  w-screen h-full  bg-white"
        data-theme="winter"
      >
        <Navbar />
        {/* Large screen content offset for sidebar */}
        <div className="w-full mt-12 lg:mt-0 lg:ml-52 py-4 px-3 lg:px-5 ">{children}</div>
      </body>
    </html>
  );
}
